const ResponseMessage = {
  DATABASE_CONNECTED: "Database connected",
  INCORRECT_PASSWORD: "Incorrect password",
  USER_EXIST: "User already exists",
  USER_FOUND: "User data fetched",
  USER_NOT_FOUND: "User not found",
  EMPLOYEE_NOT_FOUND: "Employee not found",
  EMPLOYEE_FOUND: "Employee found",
  INTERNAL_SERVER_ERROR: "Internal server error",
  SENT_OTP: "Otp sent succesfully",
  OTP_VERIFIED: "Otp Verified",
  OTP_EXPIRED: "Otp expired",
  INVALID_OTP: "Invalid otp",
  INVALID_TOKEN: "Invalid token",
  RESET_PASSWORD: "Password reset successfully",
  PASSWORD_NOT_MATCH: "Password not match",
  TOKEN_NOT_VALID: "Invalid token",
  TOKEN_REQUIRED: "Token is required for authentication",
  DATA_FOUND: "Data fetched successfully",
  DATA_NOT_FOUND: "Data not fetched ",
  USER_CREATED: "User created succesfully",
  USER_LOGGEDIN: "User logged in succesfully",
  USER_DELETED: "User deleted successfully",
  EMPLOYEE_DELETED: "Employee deleted",
  USER_UPDATED: "User details updated successfully",
  EMPLOYEE_UPDATED: "Employee details updated successfully",
  EMPLOYEE_STATUS_UPDATED: "Employee status updated successfully",
  EMAIL_EXISTS: "Email already exists",
  MOBILE_EXISTS: "This mobile number is already registered",
  DB_NOT_CONNECTED: "Database not connected",
  INCORRECT_CURR_PASSWORD: "Current password is incorrect",
  CHANGE_PASSWORD: "Change your new password",
  CODE_EXIST: "Employee code aliready exist",
  USER_STATUS_UPDATED: "User status updated succesfully",
  TASK_CREATED: "Task created succesfully",
  TASK_NOT_FOUND: "Task not found",
  TASK_DELETED: "Task deleted",
  TASK_UPDATED: "Task updated",
};

export { ResponseMessage };
